version: '3'
services:
  ledgeriumdocs:
    hostname: ledgeriumdocs
    image: 'ledgeriumengineering/mkdocs:v0.1'
    ports:
      - '8000:8000'
    volumes:
      - '.:/docs'
    entrypoint:
      - /bin/sh
      - '-c'
      - >
        set -u

        set -e

        mkdir -p /logs/mkdocs

        DATE=`date '+%Y-%m-%d_%H-%M-%S'`

        mkdocs serve --dev-addr=0.0.0.0:8000 >/logs/mkdocs/mkdocs_$${DATE}_log.txt    
    restart: always
    networks:
      test_net:
        ipv4_address: 172.19.240.43
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 128M
volumes:
  quorum-maker: ~
networks:
  test_net:
    external: true
