# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Ledgerium Blockchain
site_description: Open public implementation of Quorum Blockchain supporting public and privacy transactions.
site_author: The Blockledger Pty Ltd.
site_url: https://docs.ledgerium.io
copyright: 'Copyright &copy; 2019 The BlockLedger Pty Ltd'

# Repository
repo_name: ledgerium-io/ledgeriumdocs
repo_url: https://github.com/ledgerium-io/ledgeriumdocs/

# Page tree
nav:
  - Introduction:
      - Ledgerium Blockchain: ledgerium/introduction/ledgerium.md
      - Ledgerium Foundation: ledgerium/introduction/ledgerium_foundation.md
  
  - Ledgerium Protocol:
      - Ledgerium Core: ledgerium/ledgeriumprotocol/ledgeriumcore.md
      - Virtual Machine: ledgerium/ledgeriumprotocol/virtual_machine.md
      - Accounts: ledgerium/ledgeriumprotocol/accounts.md
      - Transactions: ledgerium/ledgeriumprotocol/transaction_processing.md
      - Gas and XLG: ledgerium/ledgeriumprotocol/gas_and_xlg.md
      - Quorum:
          - Quorum: ledgerium/ledgeriumprotocol/quorum/quorum.md
          - Tessera:
              - What is Tessera: ledgerium/ledgeriumprotocol/quorum/tessera/tessera.md
              - Configuration:
                  - Overview: ledgerium/ledgeriumprotocol/quorum/tessera/configuration/configuration_overview.md
                  - Keys Config: ledgerium/ledgeriumprotocol/quorum/tessera/configuration/keys.md
                  - TLS Config: ledgerium/ledgeriumprotocol/quorum/tessera/configuration/tls.md
                  - Using CLI to override config: ledgerium/ledgeriumprotocol/quorum/tessera/configuration/using_cli_to_override_config.md
                  - Sample Configuration: ledgerium/ledgeriumprotocol/quorum/tessera/configuration/sample_configuration.md
              - Tessera Services:
                  - Transaction Manager: ledgerium/ledgeriumprotocol/quorum/tessera/tesseraservices/transactionmanager.md
                  - Enclave: ledgerium/ledgeriumprotocol/quorum/tessera/tesseraservices/enclave.md
                  - Keys:
                      - Key Generation: ledgerium/ledgeriumprotocol/quorum/tessera/tesseraservices/keys/keys.md
                      - Setting up Hashicorp Vault: ledgerium/ledgeriumprotocol/quorum/tessera/tesseraservices/keys/setting_up_a_hashicorp_vault.md
                      - Setting up Azure Key Vault: ledgerium/ledgeriumprotocol/quorum/tessera/tesseraservices/keys/setting_up_an_azurekey_vault.md
              - Usage:
                  - Interfaces & API: ledgerium/ledgeriumprotocol/quorum/tessera/Usage/Interface & API.md
                  - Admin Usage: ledgerium/ledgeriumprotocol/quorum/tessera/Usage/Admin Usage.md
                  - Monitoring: ledgerium/ledgeriumprotocol/quorum/tessera/Usage/Monitoring.md
      - IBFT Consensus: ledgerium/ledgeriumprotocol/ibft_consensus.md
      - Network Permissioning: ledgerium/ledgeriumprotocol/network_permissioning.md
      - What is XLG: ledgerium/ledgeriumprotocol/xlg.md
      - Smart Contract: ledgerium/ledgeriumprotocol/smart_contracts.md
      
  - Ledgerium Setup:
      - Test Network: ledgerium/ledgeriumsetup/test_networks.md
      - Setup Masternode: ledgerium/ledgeriumsetup/ledgerium_masternode.md
      - Governance: ledgerium/ledgeriumsetup/ledgerium_governance.md
      - Peer permissioning: ledgerium/ledgeriumsetup/peer_permissioning_governance.md
      - XLG Reward: ledgerium/ledgeriumsetup/xlg_reward.md
      - Faucet: ledgerium/ledgerium_faucet.md
      
  - Ledgerium Applications:
      - Ledgerium BlockExplorer: ledgerium/ledgeriumapplications/ledgerium_block_explorer.md
      - Ledgerium Wallet: ledgerium/ledgeriumapplications/ledgerium_wallet.md
      - Ledgerium Tools: ledgerium/ledgeriumapplications/ledgerium_tools.md

  - Smart Contracts:
      - Accessing Contracts: ledgerium/smartcontracts/accessing_contracts.md
      - Deploying Contracts: ledgerium/smartcontracts/accessing_contracts.md
  
  - Ledgerium DApp Development:
      - DApp: ledgerium/ledgeriumdappdevelopment/decentralised_app_platform.md
      - Setup DApp Environment: ledgerium/ledgeriumdappdevelopment/setupenvironment.md
      - Solidity: ledgerium/ledgeriumdappdevelopment/solidity.md
      - Ledgerium API: ledgerium/ledgeriumdappdevelopment/json-rpc.md
      - Best Practices: ledgerium/ledgeriumdappdevelopment/bestpractices.md
  
  - Ledgerium Wallet:
      - Using Ledgerium Wallet: ledgerium/LedgeriumWallet/using_ledgerium_wallet.md
      
  - Ledgerium Box:
      - Getting Started: ledgerium/ledgeriumbox/gettingstarted.md
      - Smart Contract Deployment: ledgerium/ledgeriumbox/deploying_smart_contracts.md

  - Ledgerium Gas Station: 
    - Ledgerium Gas Station: ledgerium/Ledgeriumgasstation/ledgerium_gas_station.md
  
  - Glossary: ledgerium/glossary.md
  - Community: ledgerium/community.md
  - Latest Release: ledgerium/release.md
  - Roadmap: ledgerium/roadmap.md
  #- References: ledgerium/References.md

theme:
  name: 'material'
  custom_dir: 'material'
  font:
      text: 'Roboto'
      code: 'Roboto Mono'
  language: 'en'
  logo: 'images/logo.png'
  favicon: 'images/logo-48x48.png'

extra_css:
    - 'theme/assets/stylesheets/extra.css'

# Customization
extra:
  social:
    - type: globe
      link: https://www.ledgerium.io/
    - type: github-alt
      link: https://github.com/ledgerium-io
    - type: twitter
      link: https://twitter.com/ledgerium
    - type: linkedin
      link: https://www.linkedin.com/company/blockledger

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
